Online Banking/asp-core-mvc/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using asp_core_mvc.Models;
using Microsoft.AspNetCore.Http;

namespace asp_core_mvc.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginModel login)
        {
            if (DatabaseHandler.validateUser(login))
            {
                HttpContext.Session.SetString("Name", login.FullName);
                HttpContext.Session.SetInt32("CustomerID", login.CustomerID);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("", "Incorrect Username/Password");
                return View("Index");
            }
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index");
        }
    }
}

Online Banking/asp-core-mvc/Controllers/ReportsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using asp_core_mvc.Models;
using asp_core_mvc.ViewModels;
using System;
using OfficeOpenXml;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using System.Globalization;

namespace asp_core_mvc.Controllers
{
    public class ReportsController : Controller
    {
        private ReportsModel generateReportsModel(int account = 0)
        {
            ReportsModel reportsModel = new ReportsModel();
            Int32 customerID = (Int32)HttpContext.Session.GetInt32("CustomerID");
            List<Int32> accountIDs = DatabaseHandler.getAccounts(customerID);
            reportsModel.accounts = accountIDs;
            if (accountIDs.Count > 0)
            {
                if (account > 0)
                {
                    reportsModel.curAccount = account;
                    reportsModel.Reports = DatabaseHandler.getReports(customerID, account);
                    reportsModel.PrevReports = DatabaseHandler.getPrevReports(customerID, account);
                }
                else
                {
                    reportsModel.curAccount = accountIDs[0];
                    reportsModel.Reports = DatabaseHandler.getReports(customerID, accountIDs[0]);
                    reportsModel.PrevReports = DatabaseHandler.getPrevReports(customerID, accountIDs[0]);
                }
            }

            return reportsModel;
        }

        public IActionResult Index()
        {
            if (HttpContext.Session.Get("CustomerID") == null)
                return RedirectToAction("Index", "Login");

            return View(generateReportsModel());
        }

        [HttpPost]
        public IActionResult Index(ReportsModel reportsModel)
        {
            if (HttpContext.Session.Get("CustomerID") == null)
                return RedirectToAction("Index", "Login");

            return View(generateReportsModel(reportsModel.curAccount));
        }

        [HttpGet]
        public IActionResult Export(String sd, String ed, int accountID) // EPPlus [params = startdate, enddate]
        {
            byte[] result;

            ExcelPackage pkg = new ExcelPackage();
            ExcelWorksheet ws = pkg.Workbook.Worksheets.Add("Report");

            ws.Cells["A1"].Value = "Online Banking Report";
            ws.Cells["A3"].Value = "Start Date:";
            ws.Cells["A4"].Value = "End Date:";
            ws.Cells["A5"].Value = "Alerts Tripped:";

            ws.Cells["A7"].Value = "Date";
            ws.Cells["B7"].Value = "Reason for Alert";
            ws.Cells["C7"].Value = "Description";
            ws.Cells["D7"].Value = "Location";
            ws.Cells["E7"].Value = "Amount";
            ws.Cells["F7"].Value = "Balance";
            //ws.Cells["G7"].Value = "TransID";

            Int32 customerID = (Int32)HttpContext.Session.GetInt32("CustomerID");
            List<Reports> reps = DatabaseHandler.getPrevReports(customerID, accountID);
            ws.Cells["B3"].Value = sd; // Start Date
            ws.Cells["B4"].Value = ed; // End Date
            foreach (Reports rep in reps)
            {
                if (rep.StartDate == sd && rep.EndDate == ed)
                    ws.Cells["B5"].Value = rep.AlertsInTimePeriod;
            }
            //ws.Cells["B5"].Value = reps.Find(x => x.StartDate.Contains(sd) && x.EndDate.Contains(ed)).AlertsInTimePeriod; // Alerts Tripped

            List<Alerts> alrts = DatabaseHandler.exportAlerts(customerID, accountID);

            int startRow = 8;
            DateTime startDate = DateTime.ParseExact(sd, "MM/dd/yyyy", CultureInfo.InvariantCulture);
            DateTime endDate = DateTime.ParseExact(ed, "MM/dd/yyyy", CultureInfo.InvariantCulture);
            foreach (Alerts alrt in alrts)
            {
                DateTime alrtDate = DateTime.ParseExact(alrt.TransDate, "MM/dd/yyyy", CultureInfo.InvariantCulture);
                if (startDate <= alrtDate && alrtDate <= endDate)
                {
                    ws.Cells["A" + startRow.ToString()].Value = alrt.TransDate; // Date
                    ws.Cells["B" + startRow.ToString()].Value = alrt.Reason; // Reason for Alert
                    ws.Cells["C" + startRow.ToString()].Value = alrt.TransDesc; // Description
                    ws.Cells["D" + startRow.ToString()].Value = alrt.Location; // Location
                    ws.Cells["E" + startRow.ToString()].Value = Convert.ToDecimal(alrt.TransType + alrt.Amount); // Amount
                    ws.Cells["F" + startRow.ToString()].Value = alrt.Balance; // Balance
                    startRow++;
                }
            }

            ws.Cells["A:AZ"].AutoFitColumns();
            result = pkg.GetAsByteArray();
            string fileName = "export" + sd + "to" + ed + ".xlsx";
            return File(result, "application/vnd.ms-excel", fileName);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Online Banking/asp-core-mvc/Controllers/RulesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using asp_core_mvc.Models;
using asp_core_mvc.ViewModels;
using Microsoft.AspNetCore.Http;

namespace asp_core_mvc.Controllers
{
    public class RulesController : Controller
    {
        private RulesModel GenerateRulesModel(int account = 0)
        {
            RulesModel rulesModel = new RulesModel();
            Int32 customerID = (Int32)HttpContext.Session.GetInt32("CustomerID");
            List<Int32> accountIDs = DatabaseHandler.getAccounts(customerID);
            rulesModel.accounts = accountIDs;
            if (accountIDs.Count > 0)
            {
                if(account > 0)
                {
                    rulesModel.curAccount = account;
                    rulesModel.rules = DatabaseHandler.getRules(customerID, account);
                }
                else
                {
                    rulesModel.curAccount = accountIDs[0];
                    rulesModel.rules = DatabaseHandler.getRules(customerID, accountIDs[0]);
                }
            }
            return rulesModel;
        }

        public IActionResult Index()
        {
            if (HttpContext.Session.Get("CustomerID") == null)
                return RedirectToAction("Index", "Login");

            return View(GenerateRulesModel());
        }

        [HttpPost]
        public IActionResult Index(RulesModel ruleModel)
        {
            if (HttpContext.Session.Get("CustomerID") == null)
                return RedirectToAction("Index", "Login");

            return View(GenerateRulesModel(ruleModel.curAccount));
        }

        [HttpPost]
        public IActionResult Edit(RulesModel ruleModel)
        {
            if (HttpContext.Session.Get("CustomerID") == null)
                return RedirectToAction("Index", "Login");

            if(ruleModel.rules.startTrans < new DateTime(1900, 1, 1) ||
                ruleModel.rules.startTrans > new DateTime(9999, 12, 31))
            {
                ModelState.AddModelError("startTrans", "The field Start date must be between 1/1/1900 and 12/31/9999.");
            }
            if (ruleModel.rules.endTrans < new DateTime(1900, 1, 1) ||
                ruleModel.rules.endTrans > new DateTime(9999, 12, 31))
            {
                ModelState.AddModelError("endTrans", "The field End date must be between 1/1/1900 and 12/31/9999.");
            }

            if(ruleModel.rules.startTrans > ruleModel.rules.endTrans)
            {
                ModelState.AddModelError("startTrans", "The Start date must be before End date.");
            }

            Int32 customerID = (Int32)HttpContext.Session.GetInt32("CustomerID");
            if (!ModelState.IsValid)
            {
                ruleModel.curAccount = ruleModel.rules.accountID;
                ruleModel.accounts = DatabaseHandler.getAccounts(customerID);
                return View("Index", ruleModel);
            }

            if (ruleModel.rules.OutStateTrans == false && ruleModel.rules.rangeTrans == false &&
                ruleModel.rules.catTrans == false && ruleModel.rules.greatTrans == false &&
                ruleModel.rules.greatDepo == false && ruleModel.rules.greatWithdraw == false &&
                ruleModel.rules.greatBal == false && ruleModel.rules.lessBal == false)
                DatabaseHandler.deleteRules(customerID, ruleModel.rules.accountID);
            else
                DatabaseHandler.setRules(customerID, ruleModel.rules);

            ViewBag.Success = true;

            return View("Index", GenerateRulesModel(ruleModel.rules.accountID));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Online Banking/asp-core-mvc/Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using asp_core_mvc.Models;
using asp_core_mvc.ViewModels;

namespace asp_core_mvc.Controllers
{
    public class TransactionsController : Controller
    {
        private TransactionsModel GenerateTransactionsModel(int account = 0)
        {
            TransactionsModel transModel = new TransactionsModel();
            Int32 customerID = (Int32)HttpContext.Session.GetInt32("CustomerID");
            List<Int32> accountIDs = DatabaseHandler.getAccounts(customerID);
            transModel.accounts = accountIDs;
            if (accountIDs.Count > 0)
            {
                if (account > 0)
                {
                    transModel.curAccount = account;
                    transModel.transactions = DatabaseHandler.getTransactions(account);
                }
                else
                {
                    transModel.curAccount = accountIDs[0];
                    transModel.transactions = DatabaseHandler.getTransactions(accountIDs[0]);
                }
            }
            return transModel;
        }
        public IActionResult Index()
        {
            if (HttpContext.Session.Get("CustomerID") == null)
                return RedirectToAction("Index", "Login");

            return View(GenerateTransactionsModel());
        }

        [HttpPost]
        public IActionResult Index(TransactionsModel transModel)
        {
            if (HttpContext.Session.Get("CustomerID") == null)
                return RedirectToAction("Index", "Login");

            return View(GenerateTransactionsModel(transModel.curAccount));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        
    }
}

Online Banking/asp-core-mvc/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="refresh" content="300; url=/Login" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Online Banking</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Online Banking</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transactions" asp-action="Index">Transactions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Alerts" asp-action="Index">Alerts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rules" asp-action="Index">Rules</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reports" asp-action="Index">Reports</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>*@
                    </ul>
                </div>
                <div>
                    <form asp-controller="Login" asp-action="Logout">
                        <div class="form-group float-right" style="margin: 0 auto">
                            @Context.Session.GetString("Name")
                            <button type="submit" class="btn btn-light">Logout</button>
                        </div>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 -
            <a asp-area="" asp-controller="Home" asp-action="Index">Online Banking</a> 
            @*<a asp-area="" asp-controller="Home" asp-action="About">About</a>*@
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>